name: store_app

description: "A Flutter store application."

publish_to: "none"


version: 1.0.0+1


environment:
  sdk: ^3.5.0



dependencies:

  flutter:
    sdk: flutter


  # Icons
  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0


  # Navigation Bar
  curved_navigation_bar: ^1.0.6


  # State Management
  provider: ^6.1.5+1


  # Animation
  lottie: ^3.2.0





dev_dependencies:

  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0



flutter:

  uses-material-design: true

  assets:
    - aseets/animation/Notification.json